.PHONY: clean All

All:
	@echo "----------Building project:[ program7 - Release ]----------"
	@cd "program7" && "$(MAKE)" -f  "program7.mk"
clean:
	@echo "----------Cleaning project:[ program7 - Release ]----------"
	@cd "program7" && "$(MAKE)" -f  "program7.mk" clean
