.PHONY: clean All

All:
	@echo "----------Building project:[ program2 - Release ]----------"
	@cd "program2" && "$(MAKE)" -f  "program2.mk"
clean:
	@echo "----------Cleaning project:[ program2 - Release ]----------"
	@cd "program2" && "$(MAKE)" -f  "program2.mk" clean
